# Generated by Django 5.2.8 on 2025-11-24 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('interest', 'Interest Payment')], max_length=20)),
                ('related_object_id', models.IntegerField(help_text='ID of MonthlyMembershipDeposit or LoanInterestPayment')),
                ('client_txn_id', models.CharField(help_text='Unique transaction ID for gateway', max_length=255, unique=True)),
                ('order_id', models.BigIntegerField(blank=True, help_text='Order ID from payment gateway', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, help_text='Full response from payment gateway', null=True)),
                ('upi_txn_id', models.CharField(blank=True, help_text='UPI transaction ID from gateway', max_length=255, null=True)),
                ('txn_date', models.DateField(blank=True, help_text='Transaction date from gateway', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_txn_id'], name='app_payment_client__b20fa5_idx'), models.Index(fields=['order_id'], name='app_payment_order_i_36d294_idx'), models.Index(fields=['status'], name='app_payment_status_093bed_idx')],
            },
        ),
    ]
