# Generated by Django 5.2.8 on 2025-12-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_popup_supportticket_supportticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysetting',
            name='apk_file',
            field=models.FileField(blank=True, help_text='Upload APK file for app updates', null=True, upload_to='apk/'),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='latest_app_version',
            field=models.CharField(blank=True, default='1.0.0', help_text='Latest app version name (e.g., "1.0.1")', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='latest_version_code',
            field=models.IntegerField(default=1, help_text='Latest app version code (e.g., 1, 2, 3...)'),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='mandatory_update',
            field=models.BooleanField(default=False, help_text='Mark this update as mandatory (users cannot skip)'),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='release_notes',
            field=models.TextField(blank=True, default='Bug fixes and performance improvements', help_text="Release notes describing what's new in the update", null=True),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='update_message',
            field=models.TextField(blank=True, default='A new version is available with bug fixes and improvements.', help_text='Message shown to users when update is available', null=True),
        ),
    ]
