# Generated by Django 5.2.8 on 2025-11-29 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='due_principle_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='paid_principle_amount',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('interest', 'Interest Payment'), ('principle', 'Principle Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='related_object_id',
            field=models.IntegerField(help_text='ID of MonthlyMembershipDeposit, LoanInterestPayment, or LoanPrinciplePayment'),
        ),
        migrations.CreateModel(
            name='LoanPrinciplePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principle_payments', to='app.loan')),
            ],
            options={
                'verbose_name': 'Loan Principle Payment',
                'verbose_name_plural': 'Loan Principle Payments',
                'ordering': ['-paid_date', '-created_at'],
            },
        ),
    ]
