# Generated by Django 5.2.8 on 2025-11-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_loan_due_principle_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninterestpayment',
            name='name',
            field=models.CharField(blank=True, help_text='Auto-generated format: YYYY MMM (e.g., "2025 Oct")', max_length=50),
        ),
        migrations.AddField(
            model_name='monthlymembershipdeposit',
            name='name',
            field=models.CharField(blank=True, help_text='Auto-generated format: YYYY MMM (e.g., "2025 Apr")', max_length=50),
        ),
        migrations.AddField(
            model_name='monthlymembershipdeposit',
            name='paid_date',
            field=models.DateField(blank=True, help_text='Date when payment was completed', null=True),
        ),
    ]
