# Generated by Django 5.2.8 on 2025-12-06 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mysetting_apk_file_mysetting_latest_app_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('purpose', models.TextField()),
            ],
            options={
                'verbose_name': 'Fund Management',
                'verbose_name_plural': 'Fund Management',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OrganizationalWithdrawal',
        ),
    ]
