# Generated by Django 5.2.8 on 2025-12-06 19:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fundmanagement_delete_organizationalwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysetting',
            name='default_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Default penalty amount per month (compounds by doubling each month)', max_digits=15),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='penalty_grace_period_days',
            field=models.IntegerField(default=0, help_text='Number of days after due date before penalty is applied'),
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penalty_type', models.CharField(choices=[('deposit', 'Deposit'), ('interest', 'Interest')], max_length=20)),
                ('related_object_id', models.IntegerField(help_text='ID of MonthlyMembershipDeposit or LoanInterestPayment')),
                ('related_object_type', models.CharField(help_text='Type of related object: deposit or interest', max_length=50)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Base penalty amount from settings', max_digits=15)),
                ('month_number', models.IntegerField(help_text='Month number overdue (1, 2, 3, etc.)')),
                ('penalty_amount', models.DecimalField(decimal_places=2, help_text='Calculated penalty amount (base × 2^(month-1))', max_digits=15)),
                ('total_penalty', models.DecimalField(decimal_places=2, help_text='Total penalty amount for this payment (cumulative)', max_digits=15)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('due_date', models.DateField(help_text='Date when penalty was applied')),
                ('paid_date', models.DateField(blank=True, help_text='Date when penalty was paid', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
                'ordering': ['-due_date', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='app_penalty_user_id_03d322_idx'), models.Index(fields=['penalty_type'], name='app_penalty_penalty_13af6a_idx'), models.Index(fields=['related_object_id'], name='app_penalty_related_e3eafc_idx'), models.Index(fields=['payment_status'], name='app_penalty_payment_1744c6_idx')],
            },
        ),
    ]
