# Generated by Django 5.2.8 on 2025-12-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mysetting_default_penalty_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('interest', 'Interest Payment'), ('principle', 'Principle Payment'), ('penalty', 'Penalty')], max_length=20),
        ),
    ]
