# Generated by Django 5.2.8 on 2025-12-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name from payment gateway', max_length=255, null=True),
        ),
    ]
