# Generated by Django 5.2.8 on 2025-12-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_paymenttransaction_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticketreply',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
