# Generated by Django 5.2.8 on 2025-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_paymenttransaction_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gateway', 'Gateway/UPI')], default='gateway', help_text='Payment method: cash or gateway/UPI', max_length=20),
        ),
    ]
