# Generated by Django 5.2.8 on 2025-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlymembershipdeposit',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='If True, creates cash payment transaction when payment_status is paid'),
        ),
        migrations.AddField(
            model_name='loaninterestpayment',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='If True, creates cash payment transaction when payment_status is paid'),
        ),
        migrations.AddField(
            model_name='loanprinciplepayment',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='If True, creates cash payment transaction when payment_status is paid'),
        ),
    ]

