# Generated by Django 5.2.8 on 2025-12-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_add_is_custom_field'),
        ('app', '0009_loaninterestpayment_is_custom_and_more'),
    ]

    operations = [
    ]
